import { Metadata } from "next";

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import {
  BarChart3,
  BookOpen,
  Github,
  HelpCircle,
  Home,
  PlayCircle,
} from "lucide-react";

import "./globals.css";
import Link from "next/link";
import { generateSlug, getQuestionById } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Next.js Basic CSS Example",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <!-- Basic Meta Tags --> */}
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <title>BürgerFit - German Naturalization Test Prep</title>
        <meta
          name="description"
          content="Prepare for the German Einbürgerungstest with BürgerFit – an interactive quiz app covering civics, history, and regional knowledge. Track your progress and study smarter."
        />
        <meta
          name="keywords"
          content="Einbürgerungstest, German citizenship test, BürgerFit, German civics quiz, naturalization Germany, quiz app, German history, regional questions"
        />
        <meta name="author" content="BürgerFit Team" />

        {/* <!-- Open Graph / Facebook --> */}
        <meta
          property="og:title"
          content="BürgerFit – German Naturalization Test Prep"
        />
        <meta
          property="og:description"
          content="Interactive quiz app to help you pass the German Einbürgerungstest. Practice civics, history, and regional questions with real-time feedback."
        />
        <meta property="og:image" content="/assets/og-image.png" />
        <meta property="og:url" content="https://buergerfit.kanini.top" />
        <meta property="og:type" content="website" />

        {/* <!-- Twitter --> */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:title"
          content="BürgerFit – German Naturalization Test Prep"
        />
        <meta
          name="twitter:description"
          content="Master the German Einbürgerungstest with BürgerFit. Track your progress and learn with interactive quizzes."
        />
        <meta name="twitter:image" content="/assets/og-image.png" />

        {/* <!-- Favicon --> */}
        <link
          rel="icon"
          type="image/svg+xml"
          href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MCA1MCI+CiAgPHBhdGggZD0iTSAyNS4xODggMC4xNjYgQyAxMS42MzIgMC4xNjYgMC42MyAxMS4xNjcgMC42MyAyNC43MjMgQyAwLjYzIDM4LjI3OSAxMS42MzIgNDkuMjgxIDI1LjE4OCA0OS4yODEgQyAzOC43NDMgNDkuMjgxIDQ5Ljc0NSAzOC4yNzkgNDkuNzQ1IDI0LjcyMyBDIDQ5Ljc0NSAxMS4xNjcgMzguNzQzIDAuMTY2IDI1LjE4OCAwLjE2NiBaIE0gMzkuOTIyIDMyLjA5IEwgMjcuNjQzIDMyLjA5IEwgMjUuMTg4IDI3LjE3OSBMIDE5LjA0OCAyNy4xNzkgTCAxOS4wNDggMzkuNDU4IEwgMTUuMzY1IDM5LjQ1OCBMIDE1LjM2NSAxMi40NDQgTCAzMC4wOTkgMTIuNDQ0IEwgMzIuNTU1IDE3LjM1NiBMIDM5LjkyMiAxNy4zNTYgTCAzOS45MjIgMzIuMDkgWiI+PC9wYXRoPgo8L3N2Zz4="
        />

        {/* <!-- PWA & Mobile Optimization --> */}
        <meta name="theme-color" content="#ffffff" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="BürgerFit" />
        <link rel="apple-touch-icon" href="/assets/icon-192.png" />
        <link rel="manifest" href="/manifest.webmanifest" />

        {/* <!-- Canonical URL --> */}
        <link rel="canonical" href="https://buergerfit.kanini.top" />
      </head>

      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen bg-background text-foreground transition-colors duration-300 pb-20 md:pb-0">
            {children}

            {/* Mobile App Navigation */}
            <div className="fixed bottom-0 left-0 z-50 flex h-20 w-full items-center justify-around border-t border-border bg-background/90 px-6 backdrop-blur-xl md:hidden">
              <Link
                href="/"
                className="flex flex-col items-center gap-1 text-primary"
              >
                <Home size={22} />
                <span className="text-[10px] font-bold">Home</span>
              </Link>

              <Link
                href={`/learn/${generateSlug("0", getQuestionById("0").question.de)}`}
                className="flex flex-col items-center gap-1 text-muted-foreground"
              >
                <BookOpen size={22} />
                <span className="text-[10px] font-bold">Learn</span>
              </Link>

              <Link
                href="/mock-test"
                className="flex flex-col items-center gap-1 text-muted-foreground"
              >
                <PlayCircle size={22} />
                <span className="text-[10px] font-bold">Quiz</span>
              </Link>

              <Link
                href="/analytics"
                className="flex flex-col items-center gap-1 text-muted-foreground"
              >
                <BarChart3 size={22} />
                <span className="text-[10px] font-bold">Stats</span>
              </Link>
            </div>

            <footer className="hidden md:block border-t border-border py-12 text-center text-muted-foreground">
              <div className="flex flex-col items-center gap-4">
                <a
                  href="#"
                  className="flex items-center gap-2 hover:text-foreground transition-colors"
                >
                  <Github size={20} /> <span>View on GitHub</span>
                </a>
                <p className="text-sm">
                  © 2026 BürgerFit • Made for the Expat Community
                </p>
              </div>
            </footer>
          </div>

          <Toaster richColors position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
